/*

Cleansing tabela Domicilio
2018-07-13

*/


USE BancoDadosUFABC

DROP TABLE cleansing.Domicilio


SELECT 
	SUBSTRING([Column 0],1,2)	AS	[UNIDADE DA FEDERAÇÃO],
	SUBSTRING([Column 0],3,5)	AS	[CÓDIGO DO MUNICÍPIO],
	SUBSTRING([Column 0],8,13)	AS	[ÁREA DE PONDERAÇÃO],
	SUBSTRING([Column 0],21,8)	AS	[CONTROLE],
	SUBSTRING([Column 0],29,3)	AS	[PESO AMOSTRAL],
	SUBSTRING([Column 0],45,1)	AS	[REGIÃO GEOGRÁFICA],
	SUBSTRING([Column 0],46,2)	AS	[CÓDIGO DA MESORREGIÃO],
	SUBSTRING([Column 0],48,3)	AS	[CÓDIGO DA MICRORREGIÃO],
	SUBSTRING([Column 0],51,2)	AS	[CÓDIGO DA REGIÃO METROPOLITANA],
	SUBSTRING([Column 0],53,1)	AS	[SITUAÇÃO DO DOMICÍLIO],
	SUBSTRING([Column 0],54,2)	AS	[ESPÉCIE DE UNIDADE VISITADA],
	SUBSTRING([Column 0],56,2)	AS	[TIPO DE ESPÉCIE],
	SUBSTRING([Column 0],58,1)	AS	[DOMICÍLIO, CONDIÇÃO DE OCUPAÇÃO],
	SUBSTRING([Column 0],59,6)	AS	[VALOR DO ALUGUEL],
	SUBSTRING([Column 0],65,4)	AS	[ALUGUEL EM N DE SALÁRIOS MÍNIMOS ],
	SUBSTRING([Column 0],74,1)	AS	[MATERIAL PREDOMINANTE, PAREDES EXTERNAS],
	SUBSTRING([Column 0],75,2)	AS	[CÔMODOS, NÚMERO],
	SUBSTRING([Column 0],77,2)	AS	[DENSIDADE DE MORADOR/CÔMODO ],
	SUBSTRING([Column 0],80,2)	AS	[CÔMODOS COMO DORMITÓRIO, NÚMERO],
	SUBSTRING([Column 0],82,2)	AS	[DENSIDADE DE MORADOR DORMITÓRIO  ],
	SUBSTRING([Column 0],85,1)	AS	[BANHEIROS DE USO EXCLUSIVO, NÚMERO],
	SUBSTRING([Column 0],86,1)	AS	[SANITÁRIO OU BURACO PARA DEJEÇÕES, EXISTÊNCIA],
	SUBSTRING([Column 0],87,1)	AS	[ESGOTAMENTO SANITÁRIO, TIPO],
	SUBSTRING([Column 0],88,2)	AS	[ABASTECIMENTO DE ÁGUA, FORMA],
	SUBSTRING([Column 0],90,1)	AS	[ABASTECIMENTO DE ÁGUA, CANALIZAÇÃO],
	SUBSTRING([Column 0],91,1)	AS	[LIXO, DESTINO],
	SUBSTRING([Column 0],92,1)	AS	[ENERGIA ELÉTRICA, EXISTÊNCIA],
	SUBSTRING([Column 0],93,1)	AS	[EXISTÊNCIA DE MEDIDOR OU RELÓGIO, ENERGIA ELÉTRICA, COMPANHIA DISTRIBUIDORA],
	SUBSTRING([Column 0],94,1)	AS	[RÁDIO, EXISTÊNCIA],
	SUBSTRING([Column 0],95,1)	AS	[TELEVISÃO, EXISTÊNCIA],
	SUBSTRING([Column 0],96,1)	AS	[MÁQUINA DE LAVAR ROUPA,],
	SUBSTRING([Column 0],97,1)	AS	[GELADEIRA, EXISTÊNCIA],
	SUBSTRING([Column 0],98,1)	AS	[TELEFONE CELULAR, EXISTÊNCIA],
	SUBSTRING([Column 0],99,1)	AS	[TELEFONE FIXO, EXISTÊNCIA],
	SUBSTRING([Column 0],100,1)	AS	[MICROCOMPUTADOR, EXISTÊNCIA],
	SUBSTRING([Column 0],101,1)	AS	[MICROCOMPUTADOR COM ACESSO À INTERNET, EXISTÊNCIA],
	SUBSTRING([Column 0],102,1)	AS	[MOTOCICLETA PARA USO PARTICULAR, EXISTÊNCIA],
	SUBSTRING([Column 0],103,1)	AS	[AUTOMÓVEL PARA USO PARTICULAR, EXISTÊNCIA],
	SUBSTRING([Column 0],104,1)	AS	[ALGUMA PESSOA QUE MORAVA COM VOCÊ(S) ESTAVA MORANDO EM OUTRO PAÍS EM 31 DE JULHO DE 2010],
	SUBSTRING([Column 0],105,2)	AS	[QUANTAS PESSOAS MORAVAM NESTE DOMICÍLIO EM 31 DE JULHO DE 2010],
	SUBSTRING([Column 0],107,1)	AS	[A RESPONSABILIDADE PELO DOMICÍLIO É DE],
	SUBSTRING([Column 0],108,1)	AS	[FALECEU PESSOA],
	SUBSTRING([Column 0],109,7)	AS	[RENDIMENTO MENSAL DOMICILIAR EM JULHO DE 2010],
	SUBSTRING([Column 0],116,5)	AS	[RENDIMENTO DOMICILIAR, SALÁRIOS MÍNIMOS, EM JULHO DE 2010],
	SUBSTRING([Column 0],126,6)	AS	[RENDIMENTO DOMICILIAR PER CAPITA EM JULHO DE 2010 ],
	SUBSTRING([Column 0],134,4)	AS	[RENDIMENTO DOMICILIAR PER CAPITA, EM Nº DE SALÁRIOS MÍNIMOS, EM JULHO DE 2010],
	SUBSTRING([Column 0],143,1)	AS	[Espécie da Unidade Doméstica],
	SUBSTRING([Column 0],144,1)	AS	[ADEQUAÇÃO DA MORADIA]


into cleansing.Domicilio
from
dbo.Amostra_Domicilios_35_RMSP

-- (371820 rows affected)
-- 00:00:005


select top 1000
* from cleansing.Domicilio